import {Storage,KEYS} from "../core/storage.js";import {requireAdmin,logout,seed} from "../core/auth.js";import {$,$$,uid,now,escapeHTML,formatNumber,toast} from "../core/utils.js";
await seed();if(!requireAdmin())throw 0;
let games=Storage.get(KEYS.GAMES,[]),scripts=Storage.get(KEYS.SCRIPTS,[]),users=Storage.get(KEYS.USERS,[]),threads=Storage.get(KEYS.SUPPORT,[]),selectedThread=null;
const tabs=$$(".admin-tab"),sections={overview:$("#adminOverview"),users:$("#adminUsers"),scripts:$("#adminScripts"),categories:$("#adminCategories"),support:$("#adminSupport")};
function showTab(t){tabs.forEach(x=>x.classList.toggle("active",x.dataset.tab===t));Object.entries(sections).forEach(([k,v])=>v.classList.toggle("hidden",k!==t));if(t==="overview")renderOverview();if(t==="users")renderUsers();if(t==="scripts")renderScripts();if(t==="categories")renderCategories();if(t==="support")renderSupport()}
tabs.forEach(t=>t.onclick=()=>showTab(t.dataset.tab));$$("[data-jump]").forEach(b=>b.onclick=()=>showTab(b.dataset.jump));
function renderOverview(){$("#statsGrid").innerHTML=[["Users",users.length],["Scripts",scripts.length],["VIP",users.filter(u=>u.vip?.active&&Date.now()<u.vip.expiresAt).length],["Banned",users.filter(u=>u.status==="banned").length],["Support",threads.filter(t=>t.status==="open").length]].map(x=>`<div class="stat-card glass"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");$("#recentScripts").innerHTML=scripts.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,5).map(s=>`<div class="admin-row"><div><b>${escapeHTML(s.name)}</b><small>${escapeHTML(s.game)} · ${escapeHTML(s.category)}</small></div><span>${formatNumber(s.views)} views</span></div>`).join("")}
function renderUsers(){const q=$("#userSearch").value.toLowerCase();$("#usersList").innerHTML=users.filter(u=>[u.username,u.email].join(" ").toLowerCase().includes(q)).map(u=>`<div class="admin-row user-row"><div><b>${escapeHTML(u.username)}</b><small>${escapeHTML(u.email)} · ${escapeHTML(u.status)}</small></div><div class="row-actions"><button data-act="vip" data-id="${u.id}">VIP 30D</button><button data-act="ban7" data-id="${u.id}">Ban 7D</button><button data-act="reset" data-id="${u.id}">Reset</button><button class="danger-text" data-act="delete" data-id="${u.id}">Hapus</button></div></div>`).join("");$$("[data-act]").forEach(b=>b.onclick=()=>userAction(b.dataset.act,b.dataset.id))}
$("#userSearch").oninput=renderUsers;
function userAction(act,id){const i=users.findIndex(u=>u.id===id);if(i<0)return;const u=users[i];if(act==="delete"){if(!confirm(`Hapus ${u.username}?`))return;users.splice(i,1)}if(act==="vip"){u.vip={active:true,activatedAt:Date.now(),expiresAt:Date.now()+30*86400000};u.updatedAt=now()}if(act==="ban7"){u.status="banned";u.bannedUntil=Date.now()+7*86400000}if(act==="reset"){u.status="active";u.bannedUntil=null;u.vip={active:false,activatedAt:null,expiresAt:null}}Storage.set(KEYS.USERS,users);renderUsers();renderOverview();toast("Perubahan user disimpan.")}
function populateScriptGames(){const opts=games.map(g=>`<option value="${g.id}">${escapeHTML(g.name)}</option>`).join("");$("#scriptGame").innerHTML=opts;$("#categoryGame").innerHTML=opts}
function populateScriptCategories(){const g=games.find(x=>x.id===$("#scriptGame").value);$("#scriptCategory").innerHTML=(g?.categories||[]).map(c=>`<option value="${c.id}">${escapeHTML(c.name)}</option>`).join("");populateSub()}
function populateSub(){const g=games.find(x=>x.id===$("#scriptGame").value),c=g?.categories.find(x=>x.id===$("#scriptCategory").value);$("#scriptSubCategory").innerHTML=(c?.subCategories||[]).map(s=>`<option value="${s.id}">${escapeHTML(s.name)}</option>`).join("")}
$("#scriptGame").onchange=populateScriptCategories;$("#scriptCategory").onchange=populateSub;
function resetScriptForm(){document.querySelector("#scriptForm").reset();$("#scriptId").value="";$("#scriptFormTitle").textContent="Tambah Script";populateScriptGames();populateScriptCategories()}
function renderScripts(){scripts=Storage.get(KEYS.SCRIPTS,[]);$("#scriptsList").innerHTML=scripts.map(s=>`<div class="admin-row"><div><b>${escapeHTML(s.name)}</b><small>${escapeHTML(s.game)} · ${escapeHTML(s.category)} · ${escapeHTML(s.subCategory)}</small></div><div class="row-actions"><button data-edit="${s.id}">Edit</button><button class="danger-text" data-delete="${s.id}">Hapus</button></div></div>`).join("");$$("[data-edit]").forEach(b=>b.onclick=()=>editScript(b.dataset.edit));$$("[data-delete]").forEach(b=>b.onclick=()=>deleteScript(b.dataset.delete))}
function editScript(id){const s=scripts.find(x=>x.id===id);if(!s)return;$("#scriptId").value=s.id;$("#scriptName").value=s.name;$("#scriptGame").value=s.gameId;populateScriptCategories();$("#scriptCategory").value=s.categoryId;populateSub();$("#scriptSubCategory").value=s.subCategoryId;$("#scriptSize").value=s.size;$("#scriptVersion").value=s.version;$("#scriptDescription").value=s.description||"";$("#freeName").value=s.freeDownload?.name||"";$("#freeUrl").value=s.freeDownload?.url||"";$("#vipName").value=s.vipDownload?.name||"";$("#vipUrl").value=s.vipDownload?.url||"";$("#scriptFormTitle").textContent="Edit Script"}
function deleteScript(id){if(!confirm("Hapus script?"))return;scripts=scripts.filter(s=>s.id!==id);Storage.set(KEYS.SCRIPTS,scripts);renderScripts();renderOverview();toast("Script dihapus.")}
$("#newScriptBtn").onclick=resetScriptForm;$("#cancelScript").onclick=resetScriptForm;
$("#scriptForm").onsubmit=e=>{e.preventDefault();const g=games.find(x=>x.id===$("#scriptGame").value),c=g?.categories.find(x=>x.id===$("#scriptCategory").value),sc=c?.subCategories.find(x=>x.id===$("#scriptSubCategory").value),id=$("#scriptId").value||uid("SCR"),old=scripts.find(x=>x.id===id);const s={id,name:$("#scriptName").value.trim(),game:g?.name||"",gameId:g?.id||"",category:c?.name||"",categoryId:c?.id||"",subCategory:sc?.name||"",subCategoryId:sc?.id||"",size:$("#scriptSize").value.trim(),version:$("#scriptVersion").value.trim(),description:$("#scriptDescription").value.trim(),thumbnail:"",freeDownload:{enabled:!!$("#freeUrl").value.trim(),name:$("#freeName").value.trim()||"Download Free",url:$("#freeUrl").value.trim()},vipDownload:{enabled:!!$("#vipUrl").value.trim(),name:$("#vipName").value.trim()||"Download VIP",url:$("#vipUrl").value.trim()},likes:old?.likes||0,views:old?.views||0,createdAt:old?.createdAt||now(),updatedAt:now()};scripts=old?scripts.map(x=>x.id===id?s:x):[s,...scripts];Storage.set(KEYS.SCRIPTS,scripts);resetScriptForm();renderScripts();renderOverview();toast("Script berhasil disimpan.")};
function renderCategories(){games=Storage.get(KEYS.GAMES,[]);populateScriptGames();$("#gamesList").innerHTML=games.map(g=>`<div class="admin-row"><div><b>${escapeHTML(g.icon||"")} ${escapeHTML(g.name)}</b><small>${g.categories.length} kategori</small></div><button class="danger-text" data-game-delete="${g.id}">Hapus</button></div>`).join("");$$("[data-game-delete]").forEach(b=>b.onclick=()=>{if(games.length<=1)return toast("Minimal satu game.","error");games=games.filter(g=>g.id!==b.dataset.gameDelete);Storage.set(KEYS.GAMES,games);renderCategories();toast("Game dihapus.")})}
$("#gameForm").onsubmit=e=>{e.preventDefault();const name=$("#gameName").value.trim();if(games.some(g=>g.name.toLowerCase()===name.toLowerCase()))return toast("Game sudah ada.","error");games.push({id:name.toLowerCase().replace(/\s+/g,"-"),name,icon:$("#gameIcon").value.trim()||"G",categories:[]});Storage.set(KEYS.GAMES,games);e.target.reset();renderCategories();toast("Game ditambahkan.")};
$("#categoryForm").onsubmit=e=>{e.preventDefault();const g=games.find(x=>x.id===$("#categoryGame").value),name=$("#categoryName").value.trim();if(!g)return;g.categories.push({id:uid("CAT").toLowerCase(),name,subCategories:$("#subCategoryNames").value.split(",").map(x=>x.trim()).filter(Boolean).map(n=>({id:uid("SUB").toLowerCase(),name:n}))});Storage.set(KEYS.GAMES,games);e.target.reset();renderCategories();toast("Kategori ditambahkan.")};
function renderSupport(){threads=Storage.get(KEYS.SUPPORT,[]);$("#supportThreads").innerHTML=threads.length?threads.slice().reverse().map(t=>`<button class="thread-row" data-thread="${t.id}"><div><b>${escapeHTML(t.username)}</b><small>${escapeHTML(t.reason)}</small></div><span>${t.status}</span></button>`).join(""):"<div class='empty-state'>Belum ada chat.</div>";$$("[data-thread]").forEach(b=>b.onclick=()=>openThread(b.dataset.thread))}
function openThread(id){selectedThread=threads.find(t=>t.id===id);$("#adminChat").classList.remove("hidden");renderAdminMessages()}
function renderAdminMessages(){if(!selectedThread)return;$("#adminMessages").innerHTML=selectedThread.messages.map(m=>`<div class="message ${m.sender==="admin"?"mine":"theirs"}"><div>${escapeHTML(m.text||"")}${m.image?`<img src="${m.image}" alt="attachment">`:""}</div></div>`).join("");$("#adminMessages").scrollTop=$("#adminMessages").scrollHeight}
$("#adminChatForm").onsubmit=e=>{e.preventDefault();if(!selectedThread||!$("#adminMessage").value.trim())return;selectedThread.messages.push({id:uid("MSG"),sender:"admin",text:$("#adminMessage").value.trim(),createdAt:now()});selectedThread.updatedAt=now();Storage.set(KEYS.SUPPORT,threads);$("#adminMessage").value="";renderAdminMessages();renderSupport()};
$("#adminLogout").onclick=logout;renderOverview();
window.addEventListener("storage",e=>{if(e.key===KEYS.SUPPORT){threads=Storage.get(KEYS.SUPPORT,[]);renderSupport();if(selectedThread){selectedThread=threads.find(t=>t.id===selectedThread.id)||selectedThread;renderAdminMessages()}}});
