import {auth,adminProfile,verifyAdminPin,saveAdminPin,logoutFirebase} from "../firebase/auth.js";
import {db,collection,doc,getDocs,getDoc,setDoc,addDoc,updateDoc,deleteDoc,query,orderBy,limit,onSnapshot,serverTimestamp,increment} from "../firebase/db.js";
import {requireAdmin} from "../core/auth.js";
import {$,escapeHTML,formatNumber,toast,uid,now} from "../core/utils.js";
import {onAuthStateChanged} from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";

const session=requireAdmin(); if(!session) throw 0;
let me=null, games=[], scripts=[], users=[], reports=[], threads=[], selectedThread=null, unsubSupport=null;
const tabs=[...document.querySelectorAll('.admin-tab')];
const sections={overview:$('#adminOverview'),users:$('#adminUsers'),scripts:$('#adminScripts'),categories:$('#adminCategories'),reports:$('#adminReports'),support:$('#adminSupport'),settings:$('#adminSettings')};
const esc=escapeHTML;
const ts=d=>d?.toDate?d.toDate().toISOString():d||now();
const date=d=>{const x=d?.toDate?d.toDate():new Date(d);return Number.isNaN(x.getTime())?'-':x.toLocaleDateString('id-ID')};

onAuthStateChanged(auth,async u=>{if(!u||u.uid!==session.uid){location.href='../login.html';return}me=await adminProfile(u.uid);if(!me?.role||me.role!=='admin'){alert('Akses admin ditolak.');await logoutFirebase();return}await loadAll();showTab('overview')});

async function loadAll(){[games,scripts,users,reports]=await Promise.all([read('games'),read('scripts'),read('users'),read('reports')]);renderOverview();renderUsers();renderScripts();populateGames();renderCategories();renderReports();}
async function read(name){const snap=await getDocs(collection(db,name));return snap.docs.map(d=>({id:d.id,...d.data()}));}
function showTab(t){tabs.forEach(x=>x.classList.toggle('active',x.dataset.tab===t));Object.entries(sections).forEach(([k,v])=>v.classList.toggle('hidden',k!==t));if(t==='overview')renderOverview();if(t==='users')renderUsers();if(t==='scripts')renderScripts();if(t==='categories')renderCategories();if(t==='reports')renderReports();if(t==='support')startSupport();}
tabs.forEach(t=>t.onclick=()=>showTab(t.dataset.tab));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>showTab(b.dataset.jump));

function renderOverview(){const vip=users.filter(u=>u.vip?.active&&(!u.vip.expiresAt||new Date(u.vip.expiresAt?.toDate?u.vip.expiresAt.toDate():u.vip.expiresAt)>new Date())).length;const pending=reports.filter(r=>(r.status||'pending')==='pending').length;$('#statsGrid').innerHTML=[['Users',users.length],['Scripts',scripts.length],['VIP',vip],['Downloads',scripts.reduce((a,s)=>a+(s.downloads||0),0)],['Reports',pending]].map(x=>`<div class="stat-card glass"><span>${x[0]}</span><strong>${formatNumber(x[1])}</strong></div>`).join('');$('#recentScripts').innerHTML=scripts.slice().sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||''))).slice(0,8).map(s=>`<div class="admin-row"><div><b>${esc(s.name||'Untitled')}</b><small>${esc(s.game||'')} · ${esc(s.category||'')} · ${esc(s.status||'working')}</small></div><span>${formatNumber(s.downloads||0)} downloads</span></div>`).join('')||'<div class="empty-state">Belum ada script.</div>'}

function renderUsers(){const q=$('#userSearch').value.toLowerCase();const f=$('#userFilter').value;const list=users.filter(u=>{const text=[u.username,u.email,u.whatsapp].join(' ').toLowerCase();const vip=!!u.vip?.active;return text.includes(q)&&(f==='all'||(f==='vip'?vip:u.status===f))});$('#usersList').innerHTML=list.map(u=>{const banned=u.status==='banned';const vip=!!u.vip?.active;return `<tr><td><b>${esc(u.username||'—')}</b><br><small>${esc(u.email||'')}</small></td><td><span class="status-dot ${banned?'status-banned':''}">${banned?'Banned':'Aktif'}</span></td><td>${vip?`👑 sampai ${date(u.vip.expiresAt)}`:'Free'}</td><td>${date(u.createdAt)}</td><td><div class="row-actions"><button data-user="vip" data-id="${u.id}">VIP 30D</button><button data-user="ban7" data-id="${u.id}">7D</button><button data-user="ban14" data-id="${u.id}">14D</button><button data-user="ban30" data-id="${u.id}">30D</button><button data-user="ban99" data-id="${u.id}">99D</button><button data-user="perm" data-id="${u.id}">Permanent</button><button data-user="reset" data-id="${u.id}">Reset</button><button class="danger-btn" data-user="delete" data-id="${u.id}">Hapus</button></div></td></tr>`}).join('')||'<tr><td colspan="5">User tidak ditemukan.</td></tr>';document.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>userAction(b.dataset.user,b.dataset.id))}
$('#userSearch').oninput=renderUsers;$('#userFilter').onchange=renderUsers;
async function userAction(act,id){const ref=doc(db,'users',id);const u=users.find(x=>x.id===id);if(!u)return;if(act==='delete'){if(!confirm(`Hapus akun ${u.username}?`))return;await deleteDoc(ref)}else if(act==='vip'){await updateDoc(ref,{vip:{active:true,activatedAt:new Date(),expiresAt:new Date(Date.now()+30*86400000)},updatedAt:serverTimestamp()})}else if(act.startsWith('ban')){const days={ban7:7,ban14:14,ban30:30,ban99:99}[act];await updateDoc(ref,{status:'banned',bannedUntil:new Date(Date.now()+days*86400000),updatedAt:serverTimestamp()})}else if(act==='perm'){await updateDoc(ref,{status:'banned',bannedUntil:null,updatedAt:serverTimestamp()})}else if(act==='reset'){await updateDoc(ref,{status:'active',bannedUntil:null,vip:{active:false,activatedAt:null,expiresAt:null},updatedAt:serverTimestamp()})}await loadAll();toast('Perubahan user disimpan.')}

function populateGames(){games=games||[];const opts=games.map(g=>`<option value="${esc(g.id)}">${esc(g.name)}</option>`).join('');$('#scriptGame').innerHTML=opts;$('#categoryGame').innerHTML=opts;populateScriptCategories();}
function populateScriptCategories(){const g=games.find(x=>x.id===$('#scriptGame').value);$('#scriptCategory').innerHTML=(g?.categories||[]).map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');populateSub()}
function populateSub(){const g=games.find(x=>x.id===$('#scriptGame').value),c=g?.categories?.find(x=>x.id===$('#scriptCategory').value);$('#scriptSubCategory').innerHTML=(c?.subCategories||[]).map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}
$('#scriptGame').onchange=populateScriptCategories;$('#scriptCategory').onchange=populateSub;
function linkRow(l={},i){return `<div class="download-link-row glass" data-link-row="${i}"><div class="two-col"><label>Nama tombol<input data-link-name value="${esc(l.name||'Download')}" required></label><label>Jenis<select data-link-type><option value="free" ${l.type==='free'?'selected':''}>Free</option><option value="vip" ${l.type==='vip'?'selected':''}>VIP</option></select></label></div><label>URL<input data-link-url type="url" value="${esc(l.url||'')}" required></label><button type="button" class="danger-text remove-link">Hapus link</button></div>`}
function bindLinks(){document.querySelectorAll('.remove-link').forEach(b=>b.onclick=()=>b.closest('[data-link-row]').remove())}
function renderLinks(ls=[]){$('#downloadLinks').innerHTML=ls.map(linkRow).join('');bindLinks()}
$('#addLink').onclick=()=>{$('#downloadLinks').insertAdjacentHTML('beforeend',linkRow({name:'Download Free',type:'free',url:''},$('#downloadLinks').children.length));bindLinks()};
function resetForm(){document.querySelector('#scriptForm').reset();$('#scriptId').value='';$('#scriptFormTitle').textContent='Tambah Script';populateGames();renderLinks([])}
$('#newScriptBtn').onclick=resetForm;$('#cancelScript').onclick=resetForm;
function renderScripts(){$('#scriptsList').innerHTML=scripts.map(s=>`<div class="admin-row"><div><b>${esc(s.name||'Untitled')} ${s.featured?'★':''}</b><small>${esc(s.game||'')} · ${esc(s.category||'')} · ${esc(s.status||'working')} · v${esc(s.version||'-')}</small></div><div class="row-actions"><button data-edit="${s.id}">Edit</button><button data-toggle="${s.id}">${s.disabled?'Aktifkan':'Nonaktifkan'}</button><button class="danger-text" data-delete="${s.id}">Hapus</button></div></div>`).join('')||'<div class="empty-state">Belum ada script.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editScript(b.dataset.edit));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggleScript(b.dataset.toggle));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteScript(b.dataset.delete))}
function editScript(id){const s=scripts.find(x=>x.id===id);if(!s)return;$('#scriptId').value=s.id;$('#scriptName').value=s.name||'';$('#scriptGame').value=s.gameId||'';populateScriptCategories();$('#scriptCategory').value=s.categoryId||'';populateSub();$('#scriptSubCategory').value=s.subCategoryId||'';$('#scriptSize').value=s.size||'';$('#scriptVersion').value=s.version||'';$('#scriptStatus').value=s.status||'working';$('#scriptTags').value=(s.tags||[]).join(', ');$('#scriptDescription').value=s.description||'';$('#scriptChangelog').value=s.changelog||'';$('#scriptFeatured').checked=!!s.featured;$('#scriptDisabled').checked=!!s.disabled;renderLinks(s.downloadLinks||[]);$('#scriptFormTitle').textContent='Edit Script'}
async function toggleScript(id){const s=scripts.find(x=>x.id===id);await updateDoc(doc(db,'scripts',id),{disabled:!s.disabled,updatedAt:serverTimestamp()});await loadAll();toast(s.disabled?'Script diaktifkan.':'Script dinonaktifkan.')}
async function deleteScript(id){if(!confirm('Hapus script ini?'))return;await deleteDoc(doc(db,'scripts',id));await loadAll();toast('Script dihapus.')}
$('#scriptForm').onsubmit=async e=>{e.preventDefault();const id=$('#scriptId').value||uid('SCR');const g=games.find(x=>x.id===$('#scriptGame').value),c=g?.categories?.find(x=>x.id===$('#scriptCategory').value),sc=c?.subCategories?.find(x=>x.id===$('#scriptSubCategory').value);const links=[...document.querySelectorAll('[data-link-row]')].map(row=>({id:uid('LNK'),name:row.querySelector('[data-link-name]').value.trim(),type:row.querySelector('[data-link-type]').value,url:row.querySelector('[data-link-url]').value.trim()})).filter(x=>x.name&&x.url);const old=scripts.find(x=>x.id===id)||{};const payload={name:$('#scriptName').value.trim(),game:g?.name||'',gameId:g?.id||'',category:c?.name||'',categoryId:c?.id||'',subCategory:sc?.name||'',subCategoryId:sc?.id||'',size:$('#scriptSize').value.trim(),version:$('#scriptVersion').value.trim(),status:$('#scriptStatus').value,tags:$('#scriptTags').value.split(',').map(x=>x.trim()).filter(Boolean),description:$('#scriptDescription').value.trim(),changelog:$('#scriptChangelog').value.trim(),featured:$('#scriptFeatured').checked,disabled:$('#scriptDisabled').checked,downloadLinks:links,freeDownload:links.find(x=>x.type==='free')||{enabled:false,name:'Download Free',url:''},vipDownload:links.find(x=>x.type==='vip')||{enabled:false,name:'Download VIP',url:''},likes:old.likes||0,views:old.views||0,downloads:old.downloads||0,rating:old.rating||0,createdAt:old.createdAt||serverTimestamp(),updatedAt:serverTimestamp(),createdBy:old.createdBy||auth.currentUser.uid};await setDoc(doc(db,'scripts',id),payload,{merge:true});await loadAll();resetForm();toast('Script disimpan ke Firestore.')};

$('#gameForm').onsubmit=async e=>{e.preventDefault();const id=uid('GAME');await setDoc(doc(db,'games',id),{name:$('#gameName').value.trim(),icon:$('#gameIcon').value.trim(),categories:[],createdAt:serverTimestamp(),updatedAt:serverTimestamp()});e.target.reset();await loadAll();toast('Game ditambahkan.')};
function renderCategories(){$('#gamesList').innerHTML=games.map(g=>`<div class="admin-row"><div><b>${esc(g.icon||'')} ${esc(g.name)}</b><small>${(g.categories||[]).length} kategori</small></div><button data-del-game="${g.id}" class="danger-text">Hapus</button></div>`).join('');$('#categoryList').innerHTML=games.flatMap(g=>(g.categories||[]).map(c=>`<div class="admin-row"><div><b>${esc(g.name)} · ${esc(c.name)}</b><small>${(c.subCategories||[]).map(s=>esc(s.name)).join(', ')}</small></div></div>`)).join('')||'<div class="empty-state">Belum ada kategori.</div>';document.querySelectorAll('[data-del-game]').forEach(b=>b.onclick=()=>deleteGame(b.dataset.delGame))}
async function deleteGame(id){if(!confirm('Hapus game dan kategorinya?'))return;await deleteDoc(doc(db,'games',id));await loadAll();toast('Game dihapus.')}
$('#categoryForm').onsubmit=async e=>{e.preventDefault();const gid=$('#categoryGame').value,g=games.find(x=>x.id===gid);if(!g)return;const catId=uid('CAT');const cat={id:catId,name:$('#categoryName').value.trim(),subCategories:$('#subCategoryNames').value.split(',').map(x=>x.trim()).filter(Boolean).map(n=>({id:uid('SUB'),name:n}))};const next=[...(g.categories||[]),cat];await updateDoc(doc(db,'games',gid),{categories:next,updatedAt:serverTimestamp()});e.target.reset();await loadAll();toast('Kategori disimpan.')};

function renderReports(){$('#reportsList').innerHTML=reports.sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).map(r=>`<div class="admin-row"><div><b>${esc(r.reason||'Laporan')}</b><small>${esc(r.username||'User')} · Script ${esc(r.scriptId||'-')} · ${date(r.createdAt)}</small></div><div class="row-actions"><button data-report="resolve" data-id="${r.id}">Selesaikan</button><button data-report="dismiss" data-id="${r.id}">Tolak</button></div></div>`).join('')||'<div class="empty-state">Tidak ada laporan.</div>';document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>resolveReport(b.dataset.id,b.dataset.report))}
async function resolveReport(id,status){await updateDoc(doc(db,'reports',id),{status:status==='resolve'?'resolved':'dismissed',resolvedBy:auth.currentUser.uid,resolvedAt:serverTimestamp()});await loadAll();toast('Laporan diperbarui.')}

function startSupport(){if(unsubSupport)unsubSupport();unsubSupport=onSnapshot(query(collection(db,'supportThreads'),orderBy('updatedAt','desc'),limit(50)),snap=>{threads=snap.docs.map(d=>({id:d.id,...d.data()}));renderThreads()})}
function renderThreads(){$('#supportThreads').innerHTML=threads.map(t=>`<div class="thread-item ${selectedThread?.id===t.id?'active':''}" data-thread="${t.id}"><b>${esc(t.username||'User')}</b><small>${esc(t.reason||'Support')} · ${t.status||'open'}</small><p>${esc((t.messages||[]).at(-1)?.text||'')}</p></div>`).join('')||'<div class="empty-state">Belum ada chat.</div>';document.querySelectorAll('[data-thread]').forEach(b=>b.onclick=()=>openThread(b.dataset.thread))}
function openThread(id){selectedThread=threads.find(t=>t.id===id);if(!selectedThread)return;$('#adminChat').classList.remove('hidden');renderMessages()}
function renderMessages(){const box=$('#adminMessages');box.innerHTML=(selectedThread.messages||[]).map(m=>`<div class="admin-msg ${m.sender==='admin'?'admin':'user'}"><div>${esc(m.text||'')}</div><small>${new Date(m.createdAt?.toDate?m.createdAt.toDate():m.createdAt||Date.now()).toLocaleString('id-ID')}</small></div>`).join('');box.scrollTop=box.scrollHeight}
$('#adminChatForm').onsubmit=async e=>{e.preventDefault();if(!selectedThread)return;const text=$('#adminMessage').value.trim();if(!text)return;const msgs=[...(selectedThread.messages||[]),{id:uid('MSG'),sender:'admin',senderId:auth.currentUser.uid,text,createdAt:new Date()}];await updateDoc(doc(db,'supportThreads',selectedThread.id),{messages:msgs,updatedAt:serverTimestamp(),status:'open'});$('#adminMessage').value='';selectedThread.messages=msgs;renderMessages()};
$('#adminLogout').onclick=()=>logoutFirebase();
$('#changePinBtn').onclick=async()=>{const oldPin=prompt('PIN saat ini');if(!(await verifyAdminPin(auth.currentUser.uid,oldPin||''))){toast('PIN lama salah.','error');return}const p=prompt('PIN baru (minimal 6 digit)');if(!p||!/^\d{6,12}$/.test(p)){toast('PIN harus 6-12 digit.','error');return}await saveAdminPin(auth.currentUser.uid,p);toast('PIN admin diperbarui.')};
