import {Storage,KEYS} from "../core/storage.js";import {requireUser,logout,seed} from "../core/auth.js";import {$,escapeHTML,formatDate} from "../core/utils.js";import {scriptCard} from "../components/card.js";
await seed();const session=requireUser();if(!session)throw 0;let users=Storage.get(KEYS.USERS,[]);let user=users.find(u=>u.id===session.userId);
if(!user)logout();$("#welcomeName").textContent=user.username;const vipActive=!!user.vip?.active&&Date.now()<user.vip.expiresAt;if(!vipActive&&user.vip?.active){user.vip.active=false;Storage.set(KEYS.USERS,users)}if(vipActive)$("#vipBadge").classList.remove("hidden");
const games=Storage.get(KEYS.GAMES,[]);const allScripts=()=>Storage.get(KEYS.SCRIPTS,[]);
games.forEach(g=>$("#gameFilter").insertAdjacentHTML("beforeend",`<option value="${g.name}">${escapeHTML(g.name)}</option>`));
function updateCategories(){const val=$("#gameFilter").value;$("#categoryFilter").innerHTML='<option value="">Semua kategori</option>';games.filter(g=>!val||g.name===val).forEach(g=>g.categories.forEach(c=>$("#categoryFilter").insertAdjacentHTML("beforeend",`<option value="${escapeHTML(c.name)}">${escapeHTML(c.name)}</option>`)))}updateCategories();
function render(){let list=allScripts();const q=$("#searchInput").value.toLowerCase().trim(),game=$("#gameFilter").value,cat=$("#categoryFilter").value;if(q)list=list.filter(s=>[s.name,s.game,s.category,s.subCategory].join(" ").toLowerCase().includes(q));if(game)list=list.filter(s=>s.game===game);if(cat)list=list.filter(s=>s.category===cat);const sort=$("#sortFilter").value;const cmp={newest:(a,b)=>new Date(b.createdAt)-new Date(a.createdAt),oldest:(a,b)=>new Date(a.createdAt)-new Date(b.createdAt),mostLiked:(a,b)=>b.likes-a.likes,leastLiked:(a,b)=>a.likes-b.likes,mostViewed:(a,b)=>b.views-a.views,leastViewed:(a,b)=>a.views-b.views}[sort];list.sort(cmp);$("#resultCount").textContent=`${list.length} script`;$("#scriptGrid").innerHTML=list.map(s=>scriptCard(s,vipActive)).join("");$("#emptyState").classList.toggle("hidden",list.length>0)}
["searchInput","gameFilter","categoryFilter","sortFilter"].forEach(id=>$(("#"+id)).addEventListener("input",()=>{if(id==="gameFilter")updateCategories();render()}));render();
$("#logoutBtn").onclick=logout;$("#supportNav").onclick=()=>location.href="support.html";
const notifs=Storage.get(KEYS.NOTIFICATIONS,[]).filter(n=>n.userId===user.id);if(notifs.some(n=>!n.read)){$("#notifBadge").textContent=notifs.filter(n=>!n.read).length;$("#notifBadge").classList.remove("hidden")}
$("#notificationBtn").onclick=()=>{const p=$("#notificationPanel");p.classList.toggle("hidden");p.innerHTML=notifs.length?notifs.slice().reverse().map(n=>`<div class="notif-item"><b>${escapeHTML(n.title)}</b><small>${escapeHTML(n.message)}</small><em>${formatDate(n.createdAt)}</em></div>`).join(""):"<div class='notif-item'>Belum ada notifikasi.</div>";notifs.forEach(n=>n.read=true);Storage.set(KEYS.NOTIFICATIONS,Storage.get(KEYS.NOTIFICATIONS,[]))};
