import {Storage,KEYS} from "../core/storage.js";
import {requireUser} from "../core/auth.js";
import {$,escapeHTML,formatNumber,formatDate,toast} from "../core/utils.js";
const session=requireUser();if(!session)throw 0;
const id=new URLSearchParams(location.search).get("id"),scripts=Storage.get(KEYS.SCRIPTS,[]),s=scripts.find(x=>x.id===id);
if(!s){$("#detailContent").innerHTML="<div class='empty-state'>Script tidak ditemukan.</div>";throw 0}
const users=Storage.get(KEYS.USERS,[]),user=users.find(x=>x.id===session.userId);const vipActive=!!user?.vip?.active&&Date.now()<user.vip.expiresAt;
s.views=(s.views||0)+1;s.lastViewedAt=new Date().toISOString();Storage.set(KEYS.SCRIPTS,scripts);
let history=Storage.get(KEYS.HISTORY,[]).filter(x=>!(x.userId===user.id&&x.scriptId===s.id));history.unshift({userId:user.id,scriptId:s.id,at:new Date().toISOString()});Storage.set(KEYS.HISTORY,history.slice(0,50));
document.title=`${s.name} — Rapzpedia`;
const favs=Storage.get(KEYS.FAVORITES,[]);const liked=favs.some(x=>x.userId===user.id&&x.scriptId===s.id);
const related=scripts.filter(x=>x.id!==s.id&&(x.game===s.game||x.category===s.category)).sort((a,b)=>(b.views||0)-(a.views||0)).slice(0,3);
$("#detailContent").innerHTML=`<div class="detail-breadcrumb"><a href="user.html">Beranda</a><span>/</span><span>${escapeHTML(s.game)}</span><span>/</span><b>${escapeHTML(s.name)}</b></div><div class="detail-layout"><div><div class="detail-cover ${s.gameId}"><div class="detail-game-mark">${s.game==="Free Fire"?"FF":"ML"}</div><span class="detail-cover-label">${escapeHTML(s.game)}</span></div><div class="detail-side-meta glass"><div><span>Ukuran</span><b>${escapeHTML(s.size||"-")}</b></div><div><span>Versi</span><b>${escapeHTML(s.version||"-")}</b></div><div><span>Update</span><b>${formatDate(s.updatedAt||s.createdAt)}</b></div></div></div><article class="detail-content"><div class="eyebrow">${escapeHTML(s.game)} · ${escapeHTML(s.category)} · ${escapeHTML(s.subCategory)}</div><h1>${escapeHTML(s.name)}</h1><div class="detail-tags">${(s.tags||[s.category,s.subCategory]).map(t=>`<span>#${escapeHTML(t)}</span>`).join("")}</div><div class="detail-stats"><span>♥ ${formatNumber(s.likes)}</span><span>◉ ${formatNumber(s.views)}</span><span>↧ ${formatNumber(s.downloads||0)}</span><span>Version ${escapeHTML(s.version)}</span></div><p class="detail-description">${escapeHTML(s.description||"Tidak ada deskripsi.")}</p><div class="detail-actions"><button id="likeBtn" class="btn btn-ghost">♡ Suka</button><button id="favoriteBtn" class="btn btn-ghost">${liked?'♥ Favorit':'♡ Favorit'}</button><button id="shareInner" class="btn btn-ghost">↗ Bagikan</button></div><div class="download-box glass"><div><b>Download Center</b><small>Pilih akses yang sesuai dengan akun kamu.</small></div><div class="download-buttons">${s.freeDownload?.enabled&&s.freeDownload.url?`<a class="btn btn-primary" id="freeDownload" target="_blank" rel="noopener" href="${escapeHTML(s.freeDownload.url)}">${escapeHTML(s.freeDownload.name||"Download Free")} ↧</a>`:""}${s.vipDownload?.enabled&&s.vipDownload.url?`<a id="vipDownload" class="btn btn-vip" href="${escapeHTML(s.vipDownload.url)}">${escapeHTML(s.vipDownload.name||"Download VIP")} ✦</a>`:""}</div></div>${!vipActive&&s.vipDownload?.enabled?'<div class="vip-note">✦ Script ini menyediakan akses VIP tanpa iklan. Aktifkan VIP untuk menggunakannya.</div>':''}</article></div>${related.length?`<section class="related-section"><div class="section-title"><div><span class="mini-label">MORE LIKE THIS</span><h2>Script terkait</h2></div></div><div class="related-grid">${related.map(r=>`<a class="related-card glass" href="detail.html?id=${encodeURIComponent(r.id)}"><span class="related-mark">${r.game==="Free Fire"?'FF':'ML'}</span><span><b>${escapeHTML(r.name)}</b><small>${escapeHTML(r.game)} · ${formatNumber(r.views)} views</small></span><strong>→</strong></a>`).join('')}</div></section>`:''}`;
function share(){const url=location.href;if(navigator.share){navigator.share({title:s.name,text:`${s.name} — ${s.game}`,url}).catch(()=>{})}else{navigator.clipboard?.writeText(url);toast("URL postingan disalin.")}}
$("#shareBtn").onclick=share;$("#shareInner").onclick=share;
$("#likeBtn").onclick=()=>{s.likes=(s.likes||0)+1;Storage.set(KEYS.SCRIPTS,scripts);$("#likeBtn").textContent=`♥ Suka (${s.likes})`;toast("Like ditambahkan.")};
$("#favoriteBtn").onclick=()=>{let f=Storage.get(KEYS.FAVORITES,[]);const i=f.findIndex(x=>x.userId===user.id&&x.scriptId===s.id);if(i>=0){f.splice(i,1);$("#favoriteBtn").textContent="♡ Favorit";toast("Dihapus dari favorit.")}else{f.push({userId:user.id,scriptId:s.id,createdAt:new Date().toISOString()});$("#favoriteBtn").textContent="♥ Favorit";toast("Ditambahkan ke favorit.")}Storage.set(KEYS.FAVORITES,f)};
$("#freeDownload")?.addEventListener("click",()=>{s.downloads=(s.downloads||0)+1;Storage.set(KEYS.SCRIPTS,scripts)});
$("#vipDownload")?.addEventListener("click",e=>{if(!vipActive){e.preventDefault();toast("Akses VIP belum aktif.","error");return}s.downloads=(s.downloads||0)+1;Storage.set(KEYS.SCRIPTS,scripts)});
