import {Storage,KEYS} from "../core/storage.js";import {requireUser,logout,changePassword} from "../core/auth.js";import {$,escapeHTML,formatDate,formatNumber,toast} from "../core/utils.js";import {scriptCard} from "../components/card.js";
const session=requireUser();if(!session)throw 0;let users=Storage.get(KEYS.USERS,[]),user=users.find(u=>u.id===session.userId);if(!user){logout();throw 0}
function refresh(){users=Storage.get(KEYS.USERS,[]);user=users.find(u=>u.id===session.userId);const vip=!!user.vip?.active&&Date.now()<user.vip.expiresAt;if(user.vip?.active&&!vip){user.vip.active=false;user.vip.expiresAt=null;Storage.set(KEYS.USERS,users)}return vip}
const vip=refresh();$("#avatar").textContent=user.username.slice(0,1).toUpperCase();$("#profileUsername").textContent=user.username;$("#profileVip").textContent=vip?`VIP aktif sampai ${formatDate(user.vip.expiresAt)}`:"Akun aktif";$("#profileVipCard").innerHTML=vip?`<b>✦ VIP ACTIVE</b><span>${Math.max(0,Math.ceil((user.vip.expiresAt-Date.now())/86400000))} hari tersisa</span>`:`<b>FREE MEMBER</b><span>Upgrade untuk akses VIP</span>`;$("#dataUsername").textContent=user.username;$("#dataWhatsapp").textContent=user.whatsapp;$("#dataEmail").textContent=user.email;$("#dataStatus").textContent=user.status==="active"?"Aktif":"Dibatasi";
$("#logoutBtn").onclick=logout;$("#forgotPassword").onclick=()=>location.href="support.html?reason="+encodeURIComponent("Lupa Password Akun");
$("#passwordForm").onsubmit=async e=>{e.preventDefault();const msg=$("#passwordMessage");msg.textContent="";try{if($("#newPassword").value!==$("#newPassword2").value)throw new Error("Konfirmasi password tidak sama.");await changePassword(user.id,$("#oldPassword").value,$("#newPassword").value);msg.textContent="Password berhasil diperbarui.";msg.className="form-message success";e.target.reset()}catch(err){msg.textContent=err.message;msg.className="form-message error"}};
function renderFavorites(){const scripts=Storage.get(KEYS.SCRIPTS,[]),ids=Storage.get(KEYS.FAVORITES,[]).filter(x=>x.userId===user.id).map(x=>x.scriptId);const fav=scripts.filter(s=>ids.includes(s.id));$("#favoriteCount").textContent=`${fav.length} script`;$("#favoriteGrid").innerHTML=fav.length?fav.map(s=>scriptCard(s,vip,user.id)).join(""):"<div class='empty-state'><div class='empty-icon'>♡</div><h3>Belum ada favorit</h3><p>Simpan script yang ingin kamu akses lagi nanti.</p></div>";document.querySelectorAll("[data-favorite]").forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();let f=Storage.get(KEYS.FAVORITES,[]);f=f.filter(x=>!(x.userId===user.id&&x.scriptId===b.dataset.favorite));Storage.set(KEYS.FAVORITES,f);renderFavorites();toast("Dihapus dari favorit.")})}
function renderHistory(){const scripts=Storage.get(KEYS.SCRIPTS,[]),h=Storage.get(KEYS.HISTORY,[]).filter(x=>x.userId===user.id).sort((a,b)=>new Date(b.at)-new Date(a.at));$("#profileHistory").innerHTML=h.length?h.map(x=>{const s=scripts.find(a=>a.id===x.scriptId);return s?`<a class="profile-history-item glass" href="detail.html?id=${encodeURIComponent(s.id)}"><span class="history-mark">${s.game==="Free Fire"?'FF':'ML'}</span><span><b>${escapeHTML(s.name)}</b><small>${escapeHTML(s.game)} · Dilihat ${formatDate(x.at)}</small></span><strong>→</strong></a>`:''}).join(""):"<div class='empty-state'>Belum ada riwayat.</div>"}
document.querySelectorAll(".profile-tab").forEach(tab=>tab.onclick=()=>{document.querySelectorAll(".profile-tab").forEach(x=>x.classList.toggle("active",x===tab));document.querySelectorAll(".profile-tab-content").forEach(x=>x.classList.toggle("active",x.id===`tab-${tab.dataset.tab}`));if(tab.dataset.tab==='favorites')renderFavorites();if(tab.dataset.tab==='downloads')renderHistory()});$("#clearProfileHistory").onclick=()=>{Storage.set(KEYS.HISTORY,Storage.get(KEYS.HISTORY,[]).filter(x=>x.userId!==user.id));renderHistory();toast("Riwayat dihapus.")};
